config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/my-products", to: "pages#my_products"
  get "/my-profile", to: "pages#my_profile"
  resources :products
  resources :orders


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true

  validates :price, presence: true
  validates :adress, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # enumerable pour stocker les types d'utilisateurs (choix lors du sign up)
  # /!\ stocké en integer dans bdd donc ds table user: t.integer "user_type"
  enum user_type: %i[artisan customer]

  # on indique en validation du user_type la liste des clés de user_typeS
  validates :user_type, presence: true, inclusion: { in: User.user_types.keys }

  def current_order
    orders.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number user_type])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone_number user_type])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
    # @products = product_id(@products)
  end

  def show
    @order = Order.find(params[:id])
    @product = Product.find(@order.product.id)
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.save
    redirect_to order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:ordered_quantity, :product_id, :user_id, :total_price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
  def my_products
    @products = current_user.products
    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window_html: render_to_string(partial: "products/info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "products/marker")
      }
    end
  end
  def my_profile
    @user = current_user
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # before_action :set_params[:show, :edit, :create, :destroy]
  before_action :check_if_artisan, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
    @markers = Product.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window_html: render_to_string(partial: "products/info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "products/marker")
      }
    end
  end

  def show
    @product = Product.find(params[:id])
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.photo_id = @product.photo.key
    @product.save
    redirect_to product_path(@product)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :adress, :photo, :stock_quantity)
  end

  def set_params
    @product = Product.find(params[:id])
  end

  def check_if_artisan
    unless current_user.artisan?
      flash[:alert] = "Accès réservé aux artisans."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtisanAlleyApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.input :product_id %>
  <%= f.input :customer_id %>
  <%= f.input :ordered_quantity %>
  <%= f.input :total_price %>
  <%= f.submit %>
<% end %>

app/views/orders/show.html.erb
<div class="container w-50">
  <h1>Confirmation de Commande</h1><br>

  <h2>Merci pour votre commande</h2><br>

    <div class="image-item">
      <%= cl_image_tag @product.photo_id.to_s %>
        <div class="order-product-infos">
          <p class="fst-italic">Le numéro de votre commande est : <strong><%= @order.product_id %></strong></p>
          <p class="fst-italic">Le prix de votre commande est : <strong><%= @order.total_price %></strong></p>
        </div>
      </div>
</div>

<div class="btn">
<%= link_to "Products", products_path, class: "btn btn-gradient" %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/my_products.html.erb
<div class="container">
  <h1>My products</h1>
  <div class="cards-container">
    <div class="cards">
        <% @products.each do |product| %>
          <div class="card-trip m-3">
            <%= link_to product_path(product), class: "text-decoration-none text-reset" do %>
              <%= cl_image_tag product.photo_id.to_s, class: "product_img", crop: :fill %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= product.name %></h2>
                  <p>in stock: <%= product.stock_quantity %></p>
                </div>
                <h2><%= product.price%>€</h2>
              </div>
              <%# raise %>
            <% end %>
          </div>
        <% end %>
    </div>
    <div style="width: 40%; height: 100vh;position: sticky; top: 0; margin-left: 8px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/pages/my_profile.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<% if user_signed_in? %>
  <% if current_user.artisan? %>
    <div class="bg-light">
        <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
            <div class="card profile-card shadow  mt-4">
                <div class="card-body text-center">
                    <img src="https://via.placeholder.com/150" alt="User Profile" class="rounded-circle profile-img mb-3">
                    <h3 class="card-title mb-0"><%= @user.last_name %></h3>
                    <h3 class="card-title mb-0"><%= @user.first_name %></h3>
                    <p class="text-muted"><%= @user.user_type %></p>
                    <p class="card-text"><%= @user.phone_number %></p>
                    <div class="d-flex justify-content-center mb-3">
                        <a href="#" class="btn btn-outline-primary me-2"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="btn btn-outline-primary me-2"><i class="bi bi-linkedin"></i></a>
                        <a href="#" class="btn btn-outline-primary"><i class="bi bi-github"></i></a>
                    </div>
                    <ul class="list-group list-group-flush mb-3">
                        <li class="list-group-item bg-transparent">
                            <i class="bi bi-envelope-fill me-2"></i><%= @user.email%>
                    <div class="d-flex justify-content-between text-center mt-4">
                        <div>
                            <h5 class="mb-0"></h5>
                            <small class="text-muted"></small>
                        </div>
                        <div>
                            <h5 class="mb-0"><%= @user.products.count %></h5>
                            <small class="text-muted">Products</small>
                        </div>
                        <div>
                            <h5 class="mb-0"></h5>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                    <%=link_to'My Products', my_products_path, class: "btn btn-outline-primary"%>
                </div>
            </div>
        </div>
    </div>
  <%else%>
    <div class="bg-light">
        <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
            <div class="card profile-card shadow  mt-4">
                <div class="card-body text-center">
                    <img src="https://via.placeholder.com/150" alt="User Profile" class="rounded-circle profile-img mb-3">
                    <h3 class="card-title mb-0"><%= @user.last_name %></h3>
                    <h3 class="card-title mb-0"><%= @user.first_name %></h3>
                    <p class="text-muted"><%= @user.user_type %></p>
                    <p class="card-text"><%= @user.phone_number %></p>
                    <div class="d-flex justify-content-center mb-3">
                        <a href="#" class="btn btn-outline-primary me-2"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="btn btn-outline-primary me-2"><i class="bi bi-linkedin"></i></a>
                        <a href="#" class="btn btn-outline-primary"><i class="bi bi-github"></i></a>
                    </div>
                    <ul class="list-group list-group-flush mb-3">
                        <li class="list-group-item bg-transparent">
                            <i class="bi bi-envelope-fill me-2"></i><%= @user.email%>
                    </div>
                </div>
            </div>
        </div>
    </div>
  <%end %>
<%end %>

app/views/products/_form.html.erb
<div class="container">
  <div class="newproduct">
    <%= simple_form_for @product do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :adress,
        input_html: {data: {adress_autocomplete_target: "adress"}, class: "d-none mapboxgl-ctrl-geocoder"},
        wrapper_html: {data: {controller: "adress-autocomplete", adress_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, }
      %>
      <%= f.input :stock_quantity %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add Your Product" %>
    <% end %>
  </div>
</div>

app/views/products/_info_window.html.erb
<div class="card text-center">
  <div class="card-header">
    <p><%= cl_image_tag product.photo_id.to_s, height: 80, width: 80, crop: :fill %></p>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <p class="card-text"><%= product.price%>€</p>
    <%=link_to'Details', product_path(product), class: "btn btn-outline-primary"%>
  </div>
</div>

app/views/products/_marker.html.erb
<%= image_tag "alleyapp.png", height: 30, width: 30, alt: "Logo" %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.id %></h1>
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :adress %>
  <%= f.input :stock_quantity %>
  <%= f.input :price %>
  <%= f.submit "Edit" %>
<% end %>

app/views/products/index.html.erb
<div class="container">
  <h1>Display products</h1>
  <div class="cards-container">
    <div class="cards">
        <% @products.each do |product| %>
          <div class="card-trip m-3">
            <%= link_to product_path(product), class: "text-decoration-none text-reset" do %>
              <%= cl_image_tag product.photo_id.to_s, class: "product_img", crop: :fill %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= product.name %></h2>
                  <p>in stock: <%= product.stock_quantity %></p>
                </div>
                <h2><%= product.price%>€</h2>
              </div>
              <%# raise %>
            <% end %>
          </div>
        <% end %>
    </div>
    <div style="width: 40%; height: 100vh;position: sticky; top: 0; margin-left: 8px, margin-top: 20px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>Add A New Product</h1>
  <%= render "products/form" %>
</div>

app/views/products/show.html.erb
  <div class="container w-50">
    <%#  à faire une fois le User done <li>Selling by <%= @product.user.name %>
    <h1><%= @product.name %></h1>
    <div class="card-trip m-3">
          <%= cl_image_tag @product.photo_id.to_s, height: 500, width: 500, crop: :fill %>
          <div class="card-trip-infos">
            <div>
              <h2><%= @product.name %></h2>
              <p>in stock: <%= @product.stock_quantity %></p>
            </div>
            <h2 class="card-trip-pricing"><%= @product.price%>€</h2>
          </div>
      </div>
      <% if user_signed_in? %>
        <% if current_user.artisan? %>
          <%=link_to'Edit A Product', edit_product_path, class: "btn btn-outline-primary"%>
          <%= link_to "Delete", product_path(@product), class: "btn btn-outline-danger",
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
      <% end %>
  <%= simple_form_for @order, html: {data: {controller: "order"}} do |f| %>
    <%= f.input :ordered_quantity, input_html: { data: { action: "input->order#calculatTotal", order_target: "quantity" } } %>
    <div data-order-target="price" data-price="<%= @product.price%>"></div>
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p>Total : </p>
    <div class="total" data-order-target="total"></div>
    <%= f.hidden_field :total_price, data: { order_target: "hiddenTotal"} %>
    <%= f.submit "Order" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- Logo -->
    <%= link_to products_path, class: "navbar-brand" do %>
      <%= image_tag "logo_alleyapp50x50.jpg", alt: "Logo", class: "logo-img" %>
    <% end %>

    <!-- Toggle button for mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar content -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.artisan? %>
            <!-- Artisan Links -->
            <li class="nav-item">
            <% if request.fullpath == "/my-products" %>
              <%= link_to 'All Products', products_path, class: "btn btn-outline-light me-2" %>
            <% else %>
              <%= link_to 'My Products', my_products_path, class: "btn btn-outline-light me-2" %>
            <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'Add Products', new_product_path, class: "btn btn-outline-light" %>
            </li>
            <li class="nav-item">
              <span class="nav-link text-white">Bonjour <%= current_user.first_name %> (Artisan)</span>
            </li>
          <% else %>
            <!-- Regular User -->
            <li class="nav-item">
              <span class="nav-link text-white">Bonjour <%= current_user.first_name %></span>
            </li>
          <% end %>
        <% else %>
          <!-- Guest User -->
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light" %>
          </li>
        <% end %>
      </ul>

      <!-- Cart Button -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? && current_user.orders.any? %>
              <%= link_to order_path(current_user.current_order.id ), class: "btn btn-outline-warning position-relative" do %>
                <i class="fa-solid fa-cart-shopping"></i>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                <%= current_user.orders.count if user_signed_in? %>
              </span>
          <% end %>
        <% end %>

        </li>
      </ul>

      <% if user_signed_in? %>
        <!-- User Dropdown -->
        <div class="dropdown ms-3">
          <a href="#" class="avatar" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%=
            (current_user.artisan? ?
            '<img width="50" height="50" src="https://img.icons8.com/scribby/50/work.png" alt="work"/>' :
            '<img width="48" height="48" src="https://img.icons8.com/color/48/user.png" alt="user"/>').html_safe
          %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><%= link_to "My Profile", my_profile_path, class: "dropdown-item" %></li>
            <% if current_user.artisan? %>
            <% end %>
            <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item text-danger" %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</nav>